version: "3"
services:
  frontend:
    container_name: awesome_web
    build:
      context: ./client
      dockerfile: Dockerfile
    image: vikasraj/awesome_web
    ports:
      - "8080:8080"
    volumes:
      - '/app/node_modules'
      - ./client:/usr/app/
  backend:
    container_name: awesome_server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: vikasraj/awesome_server
    ports:
      - "3000:3000"
    volumes:
      - '/app/node_modules'
      - ./server:/usr/app/